title: "Abhishek Chothani"
logo: "images/profile.jpg"
description: "Innovative Robotics Engineer"
theme: jekyll-theme-minimal

author:
  name: "Abhishek Chothani"
  email: "abhismirai10@gmail.com"
  linkedin: "https://www.linkedin.com/in/abhishek-chothani10/"
  github: "https://github.com/abhismirai10"
  youtube: "https://www.youtube.com/@abhismirai10"
