# ----------------------------------
# _config.yml
# ----------------------------------
title: "Abhishek Chothani Portfolio"
description: "Innovative Robotics Engineer | MELBOURNE, FLORIDA"
theme: jekyll-theme-minimal  # You can try other themes: e.g. jekyll-theme-cayman, jekyll-theme-merlot, etc.

# Site Author details
author:
  name: "Abhishek Chothani"
  email: "abhismirai10@gmail.com"
  linkedin: "https://www.linkedin.com/..."   # Replace with your actual URL
  github: "https://github.com/..."           # Replace with your actual URL
  youtube: "https://youtube.com/..."         # Replace with your actual URL

# Optional: Add plugins if you want extra features like SEO or feeds
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you have a specific base URL (like if you're hosting on a project page), specify it here:
# baseurl: "/my-portfolio" 

# If you want to exclude any directories or files from the build, you can add them here
# exclude:
#   - node_modules
#   - vendor
